packaging_format = 2

id = "nodebb"
name = "NodeBB"
description.en = "Forum software built for the modern web"
description.fr = "Logiciel de forum conçu pour le Web moderne"

version = "4.0.5~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://nodebb.org"
demo = "https://try.nodebb.org"
admindoc = "https://docs.nodebb.org"
code = "https://github.com/NodeBB/NodeBB"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1500M"
ram.build = "1500M"
ram.runtime = "750M"

[install]
  
    [install.user_nodebb_version]
    ask.fr = "Quelle version souhaitez-vous installer ?"
    help.fr = "La version 4.x est la plus récente, mais peu de plugins sont compatibles (pour l'instant)."
    ask.en = "Which version do you want to install?"
    help.en = "Version 4.x is the latest, but few plugins are compatible (as of now)."
    type = "string"
    choices.v3 = "version 3.x"
    choices.v4 = "version 4.x"
    
    [install.domain]
    type = "domain"
    
    [install.path]
    type = "path"
    default = "/forum"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]

    [resources.ports]
    
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
